name: crop_forecast_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.3.2
  - lightgbm=4.3.0
  - statsmodels=0.14.1
  - joblib=1.4.2
  - fastapi=0.115.0
  - uvicorn=0.30.6
  - matplotlib=3.8.4
  - pip
  - pip:
      - pmdarima==2.0.4
      - python-multipart==0.0.9
